/arm_1/arm_controller/cartesian_velocity_command
/arm_1/arm_controller/sigma_values
/arm_1/arm_controller/velocity_command
/base_finish
/base_local_path
/base_local_path_ref
/base_local_path_status
/base_path_planner/inflated_static_obstacle_map
/base_path_with_goal
/dmp_executor/path
/execute_trajectory/status
/global_pose
/hsrb/arm_trajectory_controller/collisionable_command
/hsrb/arm_trajectory_controller/command
/hsrb/arm_trajectory_controller/follow_joint_trajectory/feedback
/hsrb/arm_trajectory_controller/follow_joint_trajectory/goal
/hsrb/arm_trajectory_controller/follow_joint_trajectory/result
/hsrb/arm_trajectory_controller/follow_joint_trajectory/status
/hsrb/arm_trajectory_controller/state
/hsrb/base_b_bumper_sensor
/hsrb/base_f_bumper_sensor
/hsrb/base_imu/data
/hsrb/base_magnetic_sensor_1
/hsrb/base_magnetic_sensor_2
/hsrb/base_magnetic_sensor_3
/hsrb/base_magnetic_sensor_4
/hsrb/base_pose
/hsrb/base_scan
/hsrb/battery_info
/hsrb/battery_state
/hsrb/command_status_led
/hsrb/command_status_led_rgb
/hsrb/command_velocity
/hsrb/drive_mode
/hsrb/grasp_state_request_action/status
/hsrb/gripper_controller/apply_force/status
/hsrb/gripper_controller/command
/hsrb/gripper_controller/follow_joint_trajectory/status
/hsrb/gripper_controller/grasp/goal
/hsrb/gripper_controller/grasp/result
/hsrb/gripper_controller/grasp/status
/hsrb/hand_camera/camera_info
/hsrb/hand_camera/image_raw
/hsrb/head_center_camera/camera_info
/hsrb/head_center_camera/image_raw
/hsrb/head_l_stereo_camera/camera_info
/hsrb/head_l_stereo_camera/image_raw
/hsrb/head_r_stereo_camera/camera_info
/hsrb/head_r_stereo_camera/image_raw
/hsrb/head_rgbd_sensor/depth_registered/camera_info
/hsrb/head_rgbd_sensor/depth_registered/image_raw
/hsrb/head_rgbd_sensor/rgb/camera_info
/hsrb/head_rgbd_sensor/rgb/image_raw
/hsrb/head_trajectory_controller/command
/hsrb/head_trajectory_controller/follow_joint_trajectory/status
/hsrb/head_trajectory_controller/state
/hsrb/impedance_control/follow_joint_trajectory/status
/hsrb/impedance_control/follow_joint_trajectory_with_config/status
/hsrb/joint_states
/hsrb/odom
/hsrb/omni_base_controller/follow_joint_trajectory/status
/hsrb/omni_base_controller/internal_state
/hsrb/omni_base_controller/state
/hsrb/pose2D
/hsrb/pressure_sensor
/hsrb/pseudo_velocity_controller/ref_joint_velocity
/hsrb/robot_state/joint_states
/hsrb/runstop_button
/hsrb/servo_states
/hsrb/wheel_odom
/hsrb/wrist_wrench/compensated
/hsrb/wrist_wrench/raw
/hsrb/wrist_wrench/readjustment_time
/map
/map_metadata
/mas_hsr_move_arm_joints_server/status
/mas_perception/detect_image/goal
/mas_perception/detect_image/result
/mas_perception/detect_image/status
/mas_perception/detection_result
/mdr_actions/perceive_plane_server/goal
/mdr_actions/perceive_plane_server/result
/mdr_actions/perceive_plane_server/status
/mdr_actions/turn_base_to_server/status
/move_arm_server/goal
/move_arm_server/result
/move_arm_server/status
/move_base/move/feedback
/move_base/move/goal
/move_base/move/result
/move_base/move/status
/move_base_server/goal
/move_base_server/result
/move_base_server/status
/move_forward_server/status
/move_group/display_planned_path
/move_group/feedback
/move_group/goal
/move_group/monitored_planning_scene
/move_group/result
/move_group/status
/move_mongodb_entries/status
/pickup/status
/pickup_server/result
/pickup_server/status
/place/status
/place_server/goal
/place_server/result
/place_server/status
/plane_convex_hull
/pose_text
/poses
/rosout
/rosout_agg
/rosplan_planner_interface/start_planning/status
/say
/static_distance_map
/static_distance_map_ref
/static_obstacle_map
/tabletop_segmentator_node/parameter_descriptions
/tabletop_segmentator_node/parameter_updates
/talk_request
/talk_request_action/status
/talking_sentence
/tf
/tf_static
